FROM python:3.6-slim

RUN apt-get update && apt-get install -y git

RUN mkdir /app

WORKDIR /app

COPY . /app/

RUN pip install -r requirements.txt

CMD ["py.test", "--cov-report", "term-missing", "--cov=./", "tests/"]