version: 2

jobs:
  test:
    working_directory: ~/nk_queue

    docker:
      - image: circleci/python:3.6.4

      - image: circleci/redis:5.0-alpine
        name: redis

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            pip install -r requirements.txt
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          name: Testing with pytest
          command: |
            py.test --cov-report term-missing --cov=./ tests/

workflows:
  version: 2
  python-test:
    jobs:
      - test
